name: Test

on:
  push:
    branches:
      - main

jobs:
  changelog-create:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Set PREVIOUS TAG 
        run: echo PREVIOUS_TAG=v0.0.1
      -
        name: Run ChangeLog-PR
        uses: Maahsome/changelog-pr-action@v1.0
        with:
          previoustag: v0.0.1
          token: ${{ secrets.GITHUB_TOKEN }}
          verbose: debug
      - 
        name: Get Artifact
        uses: actions/download-artifact@v2
        with:
          name: v0.0.0-NEXT
      -
        name: CAT File
        run: |
          cat v0.0.0-NEXT.md
          cp v0.0.0-NEXT.md changelog/v0.0.0-NEXT.md
      - name: Commit ChangeLog
        uses: EndBug/add-and-commit@v7
        with:
          add: 'changelog/v0.0.0-NEXT.md'
          committer_name: Christopher Maahs
          committer_email: cmaahs@gmail.com
          message: 'Update v0.0.0-NEXT.md running changelog'

